src/Entity/LOCATAIRE.php
<?php

namespace App\Entity;

use App\Repository\LOCATAIRERepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LOCATAIRERepository::class)]
class LOCATAIRE
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $Nom;

    #[ORM\Column(type: 'string', length: 255)]
    private $Prenom;

    #[ORM\Column(type: 'string', length: 255)]
    private $Email;

    #[ORM\Column(type: 'string', length: 14)]
    private $Telephone;

    #[ORM\Column(type: 'string', length: 255)]
    private $Adresse;

    #[ORM\Column(type: 'float')]
    private $CodePostal;

    #[ORM\OneToMany(mappedBy: 'Locataires', targetEntity: RESERVATION::class)]
    private $Reservations;

    public function __construct()
    {
        $this->Reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->Telephone;
    }

    public function setTelephone(string $Telephone): self
    {
        $this->Telephone = $Telephone;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->CodePostal;
    }

    public function setCodePostal(string $CodePostal): self
    {
        $this->CodePostal = $CodePostal;

        return $this;
    }

    /**
     * @return Collection|RESERVATION[]
     */
    public function getReservations(): Collection
    {
        return $this->Reservations;
    }

    public function addReservation(RESERVATION $reservation): self
    {
        if (!$this->Reservations->contains($reservation)) {
            $this->Reservations[] = $reservation;
            $reservation->setLocataires($this);
        }

        return $this;
    }

    public function removeReservation(RESERVATION $reservation): self
    {
        if ($this->Reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getLocataires() === $this) {
                $reservation->setLocataires(null);
            }
        }

        return $this;
    }
}

src/Controller/ParametreController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\UserRepository;

class ParametreController extends AbstractController
{
    #[Route('/parametres', name: 'parametres')]
    public function parametre(UserRepository $userRepository): Response
    {
        $utilisateurs = $userRepository->findAll();

        return $this->render('Parametres/parametres.html.twig',[
           'utilisateurs' => $utilisateurs,  
        ]);
    }
}

templates/parametre/parametre.html.twig
{% extends 'base.html.twig' %}

{% block title %}Paramétre(s){% endblock %}

{% block body %}
<div class="container-fluid">
        <div class="row">
        <div class="col-md-12">
        <center><h1>Paramétre</h1>
        <hr style="width: 20%;">
        <p>Gestion Location | 1.0 <p></center>
        </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title"><center>Liste des utilisateur(s)</center></h3>                  
                        <center>
                            <select class="form-select" size="5" aria-label="size 3 select example">
                                    {% for unUtilisateur in utilisateurs %}
                                    <option>{{unUtilisateur.email}}</option>
                                    {% endfor %}
                            </select>
                        </center> 
                        <br>
                        <center>
                            <button type="button" class="btn btn-outline-primary"><a href="/inscription">Ajouter</a></button>
                        </center>                  
                    </div>
                </div>
            </div>
            <div class="col-md-9">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Prochainement !</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}