src/Entity/Calendar.php
<?php

namespace App\Entity;

use App\Repository\CalendarRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CalendarRepository::class)]
class Calendar
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 100)]
    private $title;

    #[ORM\Column(type: 'datetime')]
    private $start;

    #[ORM\Column(type: 'datetime')]
    private $end;

    #[ORM\Column(type: 'text')]
    private $description;

    #[ORM\Column(type: 'boolean')]
    private $all_day;

    #[ORM\Column(type: 'string', length: 7)]
    private $background_color;

    #[ORM\Column(type: 'string', length: 7)]
    private $border_color;

    #[ORM\Column(type: 'string', length: 7)]
    private $text_color;

    #[ORM\OneToOne(mappedBy: 'Calendrier', targetEntity: RESERVATION::class, cascade: ['persist', 'remove'])]
    private $Reservation;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(\DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(\DateTimeInterface $end): self
    {
        $this->end = $end;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAllDay(): ?bool
    {
        return $this->all_day;
    }

    public function setAllDay(bool $all_day): self
    {
        $this->all_day = $all_day;

        return $this;
    }

    public function getBackgroundColor(): ?string
    {
        return $this->background_color;
    }

    public function setBackgroundColor(string $background_color): self
    {
        $this->background_color = $background_color;

        return $this;
    }

    public function getBorderColor(): ?string
    {
        return $this->border_color;
    }

    public function setBorderColor(string $border_color): self
    {
        $this->border_color = $border_color;

        return $this;
    }

    public function getTextColor(): ?string
    {
        return $this->text_color;
    }

    public function setTextColor(string $text_color): self
    {
        $this->text_color = $text_color;

        return $this;
    }

    public function getReservation(): ?RESERVATION
    {
        return $this->Reservation;
    }

    public function setReservation(?RESERVATION $Reservation): self
    {
        // unset the owning side of the relation if necessary
        if ($Reservation === null && $this->Reservation !== null) {
            $this->Reservation->setCalendrier(null);
        }

        // set the owning side of the relation if necessary
        if ($Reservation !== null && $Reservation->getCalendrier() !== $this) {
            $Reservation->setCalendrier($this);
        }

        $this->Reservation = $Reservation;

        return $this;
    }
}

src/Entity/RESERVATION.php
<?php

namespace App\Entity;

use App\Repository\RESERVATIONRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RESERVATIONRepository::class)]
class RESERVATION
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'datetime')]
    private $DateDebut;

    #[ORM\Column(type: 'datetime')]
    private $DateFin;

    #[ORM\Column(type: 'float')]
    private $PrixNuit;

    #[ORM\Column(type: 'float')]
    private $PrixTotal;

    #[ORM\Column(type: 'float')]
    private $NbrAdulte;

    #[ORM\Column(type: 'float')]
    private $NbrEnfant;

    #[ORM\Column(type: 'boolean')]
    private $EtatContrat;

    #[ORM\ManyToOne(targetEntity: LOCATAIRE::class, inversedBy: 'Reservations')]
    #[ORM\JoinColumn(nullable: false)]
    private $Locataires;

    #[ORM\ManyToOne(targetEntity: LOGEMENT::class, inversedBy: 'Reservations')]
    #[ORM\JoinColumn(nullable: false)]
    public $Logements;

    #[ORM\OneToOne(inversedBy: 'Reservation', targetEntity: Calendar::class, cascade: ['persist', 'remove'])]
    public $Calendrier;

    #[ORM\Column(type: 'float')]
    private $nbrJours;

    #[ORM\Column(type: 'string', length: 255)]
    private $description;

    #[ORM\Column(type: 'float')]
    private $ValeurTaxe;

    #[ORM\Column(type: 'float')]
    private $TaxeVariable;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->DateDebut;
    }

    public function setDateDebut(\DateTimeInterface $DateDebut): self
    {
        $this->DateDebut = $DateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->DateFin;
    }


    public function setDateFin(\DateTimeInterface $DateFin): self
    {
        $this->DateFin = $DateFin;

        return $this;
    }

    public function getPrixNuit(): ?string
    {
        return $this->PrixNuit;
    }

    public function setPrixNuit(string $PrixNuit): self
    {
        $this->PrixNuit = $PrixNuit;

        return $this;
    }

    public function getPrixTotal(): ?string
    {
        return $this->PrixTotal;
    }

    public function setPrixTotal(string $PrixTotal): self
    {
        $this->PrixTotal = $PrixTotal;

        return $this;
    }

    public function getNbrAdulte(): ?float
    {
        return $this->NbrAdulte;
    }

    public function setNbrAdulte(float $NbrAdulte): self
    {
        $this->NbrAdulte = $NbrAdulte;

        return $this;
    }

    public function getNbrEnfant(): ?float
    {
        return $this->NbrEnfant;
    }

    public function setNbrEnfant(float $NbrEnfant): self
    {
        $this->NbrEnfant = $NbrEnfant;

        return $this;
    }

    public function getEtatContrat(): ?bool
    {
        return $this->EtatContrat;
    }

    public function setEtatContrat(bool $EtatContrat): self
    {
        $this->EtatContrat = $EtatContrat;

        return $this;
    }

    public function getLocataires(): ?LOCATAIRE
    {
        return $this->Locataires;
    }

    public function setLocataires(?LOCATAIRE $Locataires): self
    {
        $this->Locataires = $Locataires;

        return $this;
    }

    public function getLogements(): ?LOGEMENT
    {
        return $this->Logements;
    }

    public function setLogements(?LOGEMENT $Logements): self
    {
        $this->Logements = $Logements;

        return $this;
    }

    public function getCalendrier(): ?Calendar
    {
        return $this->Calendrier;
    }

    public function setCalendrier(?Calendar $Calendrier): self
    {
        $this->Calendrier = $Calendrier;

        return $this;
    }

    public function toString(\DateTimeInterface $date): self
    {
        $date->format('Y-m-d H:i:s');

        return $this;
    }

    public function getNbrJours(): ?float
    {
        return $this->nbrJours;
    }

    public function setNbrJours(float $nbrJours): self
    {
        $this->nbrJours = $nbrJours;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getValeurTaxe(): ?float
    {
        return $this->ValeurTaxe;
    }

    public function setValeurTaxe(float $ValeurTaxe): self
    {
        $this->ValeurTaxe = $ValeurTaxe;

        return $this;
    }

    public function getTaxeVariable(): ?float
    {
        return $this->TaxeVariable;
    }

    public function setTaxeVariable(float $TaxeVariable): self
    {
        $this->TaxeVariable = $TaxeVariable;

        return $this;
    }
}

src/Form/RESERVATIONType.php
<?php

namespace App\Form;

use App\Entity\RESERVATION;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RESERVATIONType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('DateDebut')
            ->add('DateFin')
            ->add('PrixNuit')
            ->add('PrixTotal')
            ->add('NbrAdulte')
            ->add('NbrEnfant')
            ->add('EtatContrat')
            ->add('Locataires')
            ->add('Logements')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => RESERVATION::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Persistence\ManagerRegistry;
use App\Repository\RESERVATIONRepository;
use App\Form\ReservationType;
use App\Entity\RESERVATION;
use App\Entity\Calendar;
use DateTime;

class ReservationController extends AbstractController
{
    #[Route('/reservation', name: 'reservation')]
    public function reservation(RESERVATIONRepository $reservationRepository): Response
    {
        $reservations = $reservationRepository->findAll();

        $dateToday = new \DateTime("now");
        
        return $this->render('reservation/reservation.html.twig', [
            'reservations' => $reservations, 'dateToday' => $dateToday
        ]);
    }

    #[Route('/historique', name: 'historique')]
    public function historique(RESERVATIONRepository $reservationRepository): Response
    {
        $reservations = $reservationRepository->findAll();
        $dateToday = new \DateTime("now");
        
        return $this->render('reservation/historique.html.twig', [
            'reservations' => $reservations, 'dateToday' => $dateToday
        ]);
    }

    #[Route('/historique/profile/{id}', name: 'historique_profile')]
    public function profileHistorique(RESERVATIONRepository $reservationRepository, $id): Response
    {
        $reservations = $reservationRepository->find($id);
        
        return $this->render('reservation/profileHistorique.html.twig', [
            'reservations' => $reservations
        ]);
    }

    #[Route('/reservation/profile/{id}', name: 'reservation_profile')]
    public function profileReservation(RESERVATIONRepository $reservationRepository, $id): Response
    {
        $reservations = $reservationRepository->find($id);
        
        return $this->render('reservation/profileReservation.html.twig', [
            'reservations' => $reservations
        ]);
    }

    #[Route('/reservation/ajouter', name: 'reservation_ajouter')]
    public function ajouter(Request $request,ManagerRegistry $doctrine): Response
    {
        $entityManager = $doctrine->getManager();

        $reservation = new RESERVATION();

        $form = $this->createForm(ReservationType::class, $reservation);

        $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()){
               
                $event = new Calendar();
                
                //Données calendrier
                $event->setTitle($reservation->getLocataires()->getNom());
                $event->setStart($reservation->getDateDebut());
                $event->setEnd($reservation->getDateFin());
                $event->setDescription($form['Description']->getData());
                $event->setBackgroundColor($form['CouleurFond']->getData());
                $event->setBorderColor($form['CouleurBordure']->getData());
                $event->setTextColor($form['CouleurTexte']->getData());
                $event->setAllday("0");

                //Données reservation
                $reservation->setCalendrier($event);
                $reservation->setTaxeVariable($form['TaxeVariable']->getData());
                $reservation->setDescription($form['Description']->getData());
                
                //Calcule le nombres de jours en fonction de deux dates
                $firstDate  = $reservation->getDateDebut();
                $secondDate = $reservation->getDateFin();
                $intvl = $firstDate->diff($secondDate);
                $reservation->setNbrJours($intvl->days);
                
                //Calcule Prix taxe
                $nbrAdulte = $reservation->getNbrAdulte();
                $nbrNuit = $reservation->getNbrJours();
                $taxeVariable = $reservation->getTaxeVariable(); //2 étoiles classement

                $ValeurTaxe = $nbrAdulte * $nbrNuit * $taxeVariable;
                $reservation->setValeurTaxe($ValeurTaxe);
                $prixTotal = $ValeurTaxe + $reservation->getNbrJours() * $reservation->getPrixNuit();


                $reservation->setPrixTotal($prixTotal);

                $entityManager->persist($event);
                $entityManager->persist($reservation);
                $entityManager->flush();
               
                return $this->redirectToRoute('reservation');
            }
   
            return $this->render('Reservation/ajouter.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/reservation/modifier/{id}', name: 'reservation_modifier')]
    public function modifier(Request $request,ManagerRegistry $doctrine, RESERVATION $reservation,RESERVATIONRepository $reservationRepository, $id): Response
    {
        $reservation = $reservationRepository->find($id);

        $entityManager = $doctrine->getManager();

        $form = $this->createForm(ReservationType::class, $reservation);
        
        //Initialisation des champs non mappé
        $event_temp = $reservation->getCalendrier();
        $form['Description']->setData($event_temp->getDescription());
        $form['CouleurFond']->setData($event_temp->getBackgroundColor());
        $form['CouleurBordure']->setData($event_temp->getBorderColor());
        $form['CouleurTexte']->setData($event_temp->getTextColor());

        $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()){
                
                //Données calendrier
                $event = $reservation->getCalendrier();
                $event->setTitle($reservation->getLocataires()->getNom());
                $event->setStart($reservation->getDateDebut());
                $event->setEnd($reservation->getDateFin());
                $event->setDescription($form['Description']->getData());
                $event->setBackgroundColor($form['CouleurFond']->getData());
                $event->setBorderColor($form['CouleurBordure']->getData());
                $event->setTextColor($form['CouleurTexte']->getData());
                $event->setAllday("0");
                
                //Données reservation
                $reservation->setCalendrier($event);
                $reservation->setTaxeVariable($form['TaxeVariable']->getData());

                //Calcule le nombres de jours en fonction de deux dates
                $firstDate  = $reservation->getDateDebut();
                $secondDate = $reservation->getDateFin();
                $intvl = $firstDate->diff($secondDate);

                $reservation->setNbrJours($intvl->days);

                
                //Calcule le nombres de jours en fonction de deux dates
                $firstDate  = $reservation->getDateDebut();
                $secondDate = $reservation->getDateFin();
                $intvl = $firstDate->diff($secondDate);
                $reservation->setNbrJours($intvl->days);
                
                //Calcule Prix taxe
                $nbrAdulte = $reservation->getNbrAdulte();
                $nbrNuit = $reservation->getNbrJours();
                $taxeVariable = $reservation->getTaxeVariable(); //2 étoiles classement

                $ValeurTaxe = $nbrAdulte * $nbrNuit * $taxeVariable;
                $reservation->setValeurTaxe($ValeurTaxe);
                $prixTotal = $ValeurTaxe + $reservation->getNbrJours() * $reservation->getPrixNuit();

                $reservation->setPrixTotal($prixTotal);

                $reservation->setDescription($form['Description']->getData());
                

                $entityManager->persist($event);
                $entityManager->persist($reservation);
                $entityManager->flush();
               
                return $this->redirectToRoute('reservation');
            }
        return $this->render('Reservation/modifier.html.twig', [
            'form' => $form->createView(),'reservation' => $reservation
        ]);
    }

    #[Route('/reservation/supprimer/{id}', name: 'reservation_supprimer')]
    public function supprimer(Request $request,ManagerRegistry $doctrine, RESERVATION $reservation ,RESERVATIONRepository $reservationRepository, $id): Response
    {
        $reservation = $reservationRepository->find($id);

        $entityManager = $doctrine->getManager();
                         
        $entityManager->remove($reservation->getCalendrier());
        $entityManager->remove($reservation);
        $entityManager->flush();
               
        return $this->redirectToRoute('reservation');
    }
}

templates/Reservation/historique.html.twig
{% extends 'base.html.twig' %}

{# Compte le nombres d'historiques #}
{% set nbrHistoriques = 0 %}
{% for uneReservations in reservations %}
	{% if dateToday|date("m/d/Y") > uneReservations.DateFin|date("m/d/Y") %}
	{% set nbrHistoriques = nbrHistoriques + 1 %}
	{% endif %}
{% endfor %}

{% block title %}Historique des réservations{% endblock %}

{% block header %}
	<center><h3>{{nbrHistoriques}} réservation(s)</h3></center>
{% endblock %}

{% block body %}
    <div class="row">
		<div class="col-md-12">
			<center><h2>Historique de réservations</h2></center>
			<table class="table table-striped">
				<thead>
					<tr>
						<th style="width: 13%;"><strong>Logement</strong></th>
						<th style="width: 13%;"><strong>Locataire</strong></th>
                        <th style="width: 6%;"><strong>Début</strong></th>
                        <th style="width: 6%;"><strong>Fin</strong></th>
						<th style="width: 5%;"><strong>Taxe variable</strong></th>
                        <th style="width: 5%;"><strong>Prix de la nuit</strong></th>
						<th style="width: 5%;"><strong>Prix taxe</strong></th>
						<th style="width: 5%;"><strong>Prix total</strong></th>
                        <th style="width: 7%;"></th>
					</tr>
				</thead>
				<tbody>
				{# Afficher tous les historiques #}
				{% for uneReservations in reservations %}
					{% if dateToday|date("m/d/Y") > uneReservations.DateFin|date("m/d/Y") %}
					<tr>
                    	<th scope="row"><a href="{{path('logement_profile', {id:uneReservations.logements.id})}}">{{uneReservations.logements.Nom}}</a></th>
						<th scope="row"><a href="{{path('locataire_profile', {id:uneReservations.locataires.id})}}">{{uneReservations.Locataires.Nom}}</a></th>
                        <th scope="row">{{uneReservations.DateDebut|date("m/d/Y")}}</th>
                        <th scope="row">{{uneReservations.DateFin|date("m/d/Y")}}</th>
                        <th scope="row">{{uneReservations.TaxeVariable}} €</th>
						<th scope="row">{{uneReservations.PrixNuit}} €</th>
						<th scope="row">{{uneReservations.ValeurTaxe}} €</th>
                        <th scope="row">{{uneReservations.PrixTotal}} €</th>
                        <th scope="row">
                            <div class="btn-group" role="group" aria-label="Basic outlined example">
								<button type="button" class="btn btn-outline-primary"><a href="{{path('historique_profile', {id:uneReservations.id})}}">Voir</a></button>
							</div>
                        </th>
					</tr>
					{% endif %}
				{% endfor %}
				{% if nbrHistoriques == 0 %}
						<center><p>Aucune réservation dans l'historique !</p></center>
					{% endif %}
				</tbody>
			</table>
		</div>
	</div>
{% endblock %}

templates/Reservation/profileHistorique.html.twig
{% extends 'base.html.twig' %}

{% block title %}Historique | Profile{% endblock %}

{% block body %}
<div style="margin-top: 60px;">
    <div class="container-fluid">
	<div class="row">
    <center><h2>Historique : </h2><center><br><br>
		<div class="col-md-1">
		</div>
		<div class="col-md-10">
			<div class="row">
				<div class="col-md-8">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Informations générales</h5>
                            <hr>
                            <br>
                            <table style="width: 100%;">
                                <tr>
                                    <th style="width: 40%;padding-right: 5%;">
                                        <center><input class="form-control form-control-sm" type="text" value="{{reservations.locataires.Nom}}" aria-label="Disabled input example" disabled readonly></center>
                                    </th>
                                    <th style="width: 40%;">
                                        <center><input class="form-control form-control-sm" type="text" value="{{reservations.logements.Nom}}" aria-label="Disabled input example" disabled readonly></center>
                                    </th>
                                </tr>
                            </table>
                            <table>
                                <tr>
                                    <th style="width: 10%;padding-right: 5%;">
                                        <input type="checkbox" value="{{reservations.EtatContrat}}">
                                    </th>
                                </tr>
                            </table>
                            <br>
                            <hr>
                            <center>
                            <table>
                                <tr>
                                    <th style="width: 20%;padding-right: 5%;">
                                        <center>
                                            <h6 class="card-subtitle mb-2 text-muted">Quantité(s)</h6>
                                            <p>Nombre d'adulte(s)</p>
                                            <center><input class="form-control form-control-sm" type="text" value="{{reservations.nbrAdulte}}" aria-label="Disabled input example" disabled readonly></center>
                                            <br>
                                            <p>Nombre d'enfant(s)</p>
                                            <center><input class="form-control form-control-sm" type="text" value="{{reservations.nbrEnfant}}" aria-label="Disabled input example" disabled readonly></center>
                                        </center>
                                    </th>
                                    <th style="width: 40%;padding-right: 5%;">
                                        <center>
                                            <h6 class="card-subtitle mb-2 text-muted">Prix</h6>
                                            <p>Prix de la nuit</p>
                                            <center><input class="form-control form-control-sm" type="text" value="{{reservations.PrixNuit}} €" aria-label="Disabled input example" disabled readonly></center>
                                            <br>
                                            <p>Taxe Variable</p>
                                            <center><input class="form-control form-control-sm" type="text" value="{{reservations.TaxeVariable}} €" aria-label="Disabled input example" disabled readonly></center>
                                        </center>
                                    </th>
                                    <th style="width: 20%;padding-right: 5%;">
                                        <center>
                                            <h6 class="card-subtitle mb-2 text-muted">Couleur</h6>
                                            <p>Réservation</p>
                                            <center><input class="form-control form-control-sm" type="color" value="{{reservations.Calendrier.backgroundColor}}" aria-label="Disabled input example" disabled readonly></center>
                                            <p>Bordure</p>
                                            <center><input class="form-control form-control-sm" type="color" value="{{reservations.Calendrier.borderColor}}" aria-label="Disabled input example" disabled readonly></center>
                                            <p>Texte</p>
                                            <center><input class="form-control form-control-sm" type="color" value="{{reservations.Calendrier.textColor}}" aria-label="Disabled input example" disabled readonly></center>
                                        </center>
                                    </th>
                                </tr>
                            </table>
                            </center>
                            <br>
                            <hr>
                            <br>
                            <center><h6 class="card-subtitle mb-2 text-muted">Description</h6></center>
                            <center><input class="form-control form-control-sm" type="text" value="{{reservations.description}}" aria-label="Disabled input example" disabled readonly></center>
                        </div>
                    </div>       
                                
                 

				</div>
				<div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Période</h5>
                            <hr>
                                <center><h6 class="card-subtitle mb-2 text-muted">Début</h6></center>
                                <center><input class="form-control form-control-sm" type="text" value="{{reservations.DateDebut|date("m/d/Y")}}" aria-label="Disabled input example" disabled readonly></center>
                                <br>
                                <center><h6 class="card-subtitle mb-2 text-muted">Fin</h6></center>
                                <center><input class="form-control form-control-sm" type="text" value="{{reservations.DateFin|date("m/d/Y")}}" aria-label="Disabled input example" disabled readonly></center>
                                <br>
                                <br>
                                <center><h6 class="card-subtitle mb-2 text-muted">Nombre de jour(s)</h6></center>
                                <center><input class="form-control form-control-sm" type="text" value="{{reservations.NbrJours}} j" aria-label="Disabled input example" disabled readonly></center>
                            <br>
                            <hr>
                            <br>
                            <center>
							<div style="margin-left: 20px;"class="btn-group" role="group" aria-label="Basic outlined example">
								<button type="button" class="btn btn-outline-primary"><a href="{{path('historique')}}">Retour</a></button>
							</div>
							</center>
                        </div>
                    </div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-8">

				</div>
				<div class="col-md-4">

				</div>
			</div>
		</div>
		<div class="col-md-1">
		</div>
	</div>
</div>
{% endblock %}

templates/Reservation/reservation.html.twig
{% extends 'base.html.twig' %}

{# Compte le nombres de locataires #}
{% set nbrReservations = 0 %}
{% for uneReservations in reservations %}
	{% if dateToday|date("m/d/Y") < uneReservations.DateFin|date("m/d/Y") %}
	{% set nbrReservations = nbrReservations + 1 %}
	{% endif %}
{% endfor %}

{% block title %}Liste des réservation(s){% endblock %}

{% block header %}
	<center><h3>{{nbrReservations}} réservation(s)</h3></center>
{% endblock %}

{% block body %}
    <div class="row">
		<div class="col-md-12">
			<center><h2>Liste de réservation(s)</h2></center>
			<table class="table table-striped">
				<thead>
					<tr>
						<th style="width: 13%;"><strong>Logement</strong></th>
						<th style="width: 13%;"><strong>Locataire</strong></th>
						<th style="width: 6%;"><strong>Début</strong></th>
						<th style="width: 6%;"><strong>Fin</strong></th>
						<th style="width: 5%;"><strong>Nombre de jour(s)</strong></th>
						<th style="width: 5%;"><strong>Prix à la nuit</strong></th>
						<th style="width: 7%;"><strong>Taxe de séjour</strong></th>
						<th style="width: 7%;"><strong>Prix du séjour</strong></th>
						<th style="width: auto;"><strong>Commentaires</strong></th>
						<th style="width: 5%;"></th>
					</tr>
				</thead>
				<tbody>
				{# Afficher tous les réservations à venir #}
				{% for uneReservations in reservations %}
				{% if dateToday|date("m/d/Y") < uneReservations.DateFin|date("m/d/Y") %}
					<tr>
						<th scope="row"><a href="{{path('logement_profile',{id:uneReservations.Logements.id})}}">{{uneReservations.Logements.Nom}}</a></th>
						<th scope="row"><a href="{{path('locataire_profile',{id:uneReservations.locataires.id})}}">{{uneReservations.locataires.Nom}}</a></th>
						<th scope="row">{{uneReservations.DateDebut|date("m/d/Y")}}</th>
						<th scope="row">{{uneReservations.DateFin|date("m/d/Y")}}</th>

						<th scope="row">{{uneReservations.nbrJours}} j</th>
                        <th scope="row">{{uneReservations.PrixNuit}} €</th>
						<th scope="row">{{uneReservations.ValeurTaxe}} €</th>
						<th scope="row">{{uneReservations.PrixTotal}} €</th>
						<th scope="row"><input class="form-control form-control-sm" type="text" value="{{uneReservations.Description}}" aria-label="Disabled input example" disabled readonly></th>
				
						<th scope="row">
							<div class="btn-group" role="group" aria-label="Basic outlined example">
								<button type="button" class="btn btn-outline-primary"><a href="{{path('reservation_profile', {id:uneReservations.id})}}">Voir</a></button>
							</div>
						{% endif %}
                    {% endfor %}
						</th>
					</tr>
				{% if nbrReservations == 0 %}
					<center><p>Aucune réservation !</p></center>
				{% endif %}
				</tbody>
			</table>
			<center>
				<div class="btn-group" role="group" aria-label="Basic outlined example">
					<button type="button" class="btn btn-outline-primary"><a href="/reservation/ajouter">Ajouter</a></button>
				</div>
			</center>
		</div>
	</div>
{% endblock %}